name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/nobble-buttons/docs:latest

      # # Set container image visibility to private
      # - name: Install GitHub CLI
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'

      # - run: npm install -g @githubnext/github-cli

      # - name: Set container image visibility to private
      #   run: gh api -X PATCH "repos/nobble-buttons/webspace/packages/container/webspace/visibility" -f visibility=private
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}